FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json /app/

RUN yarn
COPY . /app

RUN yarn build:prod

FROM nginx:alpine
COPY dynamic-env.json /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/BookStore/browser /usr/share/nginx/html


# abordagem mais simples, mas não é a mais recomendada
# FROM nginx:alpine
# WORKDIR /app
# COPY dist/BookStore /usr/share/nginx/html
# COPY dynamic-env.json /usr/share/nginx/html
# COPY /nginx.conf  /etc/nginx/conf.d/default.conf